language: cpp

include: &toolchain_linux_cross
  dist: trusty
  sudo: required # for dpkg --add-architecture locking
  
# armhf toolchain
include: &toolchain_linux_armhf
  <<: *toolchain_linux_cross
  env:
    - LABEL=armhf_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=armhf
    - NPM_ARCH=arm
    - GNU_TRIPLET=arm-linux-gnueabihf
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=arm-linux-gnueabihf-g++
    - GCC_COMPILER=arm-linux-gnueabihf-gcc

matrix:
  include:
  - os: linux
    <<: *toolchain_linux_armhf

notifications:
  email: false

before_install:
  - export CXX="${GPP_COMPILER}" CC="${GCC_COMPILER}";
  - sudo rm -rf /etc/apt/sources.list.d/**;
  - sudo rm /etc/apt/sources.list;
  - echo "deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee /etc/apt/sources.list;
  - echo "deb [arch=${ARCH}] http://ports.ubuntu.com/ubuntu-ports xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list;
  - echo "deb-src http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list;
  - sudo dpkg --add-architecture ${ARCH};
  - sudo apt-get update -yq;
  - sudo apt-get install -y gcc-${GNU_TRIPLET};
  - sudo apt-get install -y g++-${GNU_TRIPLET};
  - sudo apt-get install -y pkg-config-${GNU_TRIPLET};
  - sudo apt-get install -y crossbuild-essential-${ARCH};
  - sudo apt-get install -y g++-multilib-${GNU_MULTILIB_TRIPLET};
  - sudo apt-get install -y gcc-multilib-${GNU_MULTILIB_TRIPLET};
  - sudo apt-get install -y dpkg-dev;
  - sudo apt-get install -y libgcc1;
  - sudo apt-get install -y libgcc1:${ARCH};
  - sudo apt-get install -y dpkg-cross;
  - sudo apt-get install -y cmake

script:
  cmake ./ && make
